### ISSUE TITLE
Please consider using buildx

### ISSUE THREAD

**Issue by rverma-nsl** [hairyhenderson/dockerfiles#351]
For the unfortunate M1 arm64 users :(. Great libraries by the way.

**Comment by hairyhenderson** [comment]
thanks @rverma-nsl - which images in particular are you using?

**Comment by tomaswarynyca** [comment]
Add builx for upx please
Platform: linux/amd64 linux/arm64 linux/arm/v7

**Comment by hairyhenderson** [comment]
@tomaswarynyca No need to use buildx to get those platforms. But sure I can ship those.

**Comment by hairyhenderson** [comment]
> @tomaswarynyca No need to use buildx to get those platforms. But sure I can ship those.

err... my bad, no I do need to use buildx to get those platforms 😂 (I build the upx image with bashbrew, which is the tool used for official images, but using it to build multi-platform images requires builder machines capable of doing each platform which I don't have)

**Comment by hairyhenderson** [comment]
@tomaswarynyca I did a bit of experimentation with it, and it turns out there's no Alpine packages for UPX for ARM (see https://pkgs.alpinelinux.org/packages?name=upx). Without those, it's impossible for me to add those.
